"""add_market_condition_and_is_active

Revision ID: 24bb08449268
Revises: b83582451585
Create Date: 2025-11-22 17:27:26.011855

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '24bb08449268'
down_revision: Union[str, Sequence[str], None] = 'b83582451585'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('markets', sa.Column('condition', sa.Enum('LE', 'GE', name='marketcondition'), nullable=False))
    op.add_column('markets', sa.Column('is_active', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('markets', 'is_active')
    op.drop_column('markets', 'condition')
    # ### end Alembic commands ###
