"""add token_id to markets

Revision ID: 25b23ab423ef
Revises: 24bb08449268
Create Date: 2025-11-22 18:43:34.906814

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '25b23ab423ef'
down_revision: Union[str, Sequence[str], None] = '24bb08449268'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('markets', sa.Column('token_id', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('markets', 'token_id')
    # ### end Alembic commands ###
