"""add created_at to users

Revision ID: a0447c094db3
Revises: cafa5ed1a116
Create Date: 2025-11-22 13:52:05.268272

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a0447c094db3'
down_revision: Union[str, Sequence[str], None] = 'cafa5ed1a116'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # SQLite restriction: cannot add non-constant default with ALTER TABLE unless it is null
    # Workaround: Add nullable column, populate it, then set not null (requires batch mode for sqlite usually)
    
    # However, for CURRENT_TIMESTAMP specifically, some sqlite versions are picky.
    # Simplest fix for SQLite limitation on ADD COLUMN with DEFAULT is to use a constant or allow nulls first.
    # But server_default=sa.text('(CURRENT_TIMESTAMP)') is dynamic in SQL sense but constant for the row.
    # The issue is specifically "Cannot add a column with non-constant default".
    # CURRENT_TIMESTAMP is considered non-constant by some SQLite versions in this context.
    
    # Let's try making it nullable first, or use batch operations (recommended for SQLite).
    
    with op.batch_alter_table('users') as batch_op:
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users') as batch_op:
        batch_op.drop_column('created_at')
    # ### end Alembic commands ###
