"""create_markets_table

Revision ID: b83582451585
Revises: a0447c094db3
Create Date: 2025-11-22 14:19:22.672125

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b83582451585'
down_revision: Union[str, Sequence[str], None] = 'a0447c094db3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('markets',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('market_id', sa.String(), nullable=False),
    sa.Column('market_url', sa.String(), nullable=False),
    sa.Column('market_title', sa.String(), nullable=True),
    sa.Column('target_price', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_markets_user_id'), 'markets', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_markets_user_id'), table_name='markets')
    op.drop_table('markets')
    # ### end Alembic commands ###
